[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
udie = "7Ws6fZivk9af1CPRxFsUyY5wytyZLMFjZqJgYybaNf9j"

[programs.devnet]
udie = "7Ws6fZivk9af1CPRxFsUyY5wytyZLMFjZqJgYybaNf9j"

[registry]
url = "https://api.rizilab.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rizary/turbin3/turbin3_q1_25/udie/tests/wallets/admin-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 1000000
